name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  validate:
    name: Composer validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"

      - name: Validate composer.json
        run: composer validate

  extension-verifier:
    name: Extension Verifier
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version-selection: [lowest, highest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check extension
        uses: shopware/github-actions/extension-verifier@main
        with:
          action: check
          check-against: ${{ matrix.version-selection }}
